apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: happa-staging
  namespace: giantswarm
  labels:
    app: happa-staging
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: happa-staging
    spec:
      volumes:
        - name: giantswarm-cert
          secret:
            secretName: giantswarm-cert
      containers:
      - name: happa-staging
        image: registry.giantswarm.io/giantswarm/happa:%%DOCKER_TAG%%
        volumeMounts:
        - name: giantswarm-cert
          mountPath: /etc/nginx/certs
          readOnly: true
        env:
        - name: PASSAGE_ENDPOINT
          value: https://passage-g8s.giantswarm.io
        - name: API_ENDPOINT
          value: https://api-g8s.giantswarm.io
        - name: DESMOTES_ENDPOINT
          value: https://desmotes-g8s.giantswarm.io
        - name: ENVIRONMENT
          value: kubernetes
        livenessProbe:
          httpGet:
            path: /
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 10
          timeoutSeconds: 1
      imagePullSecrets:
      - name: circleci-giantswarm-registry

---

apiVersion: v1
kind: Service
metadata:
  name: happa-staging
  namespace: giantswarm
  labels:
    app: happa-staging
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    app: happa-staging

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: happa-staging
  namespace: giantswarm
  labels:
    app: happa-staging
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: staging.happa.giantswarm.io
    http:
      paths:
      - backend:
          serviceName: happa-staging
          servicePort: 8000
        path: /
  tls:
  - hosts:
    - staging.happa.giantswarm.io