{{- if not (((.Values.global).podSecurityStandards).enforced) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "fe-docs.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    app: {{ include "fe-docs.name" . }}
rules:
- apiGroups:
  - extensions
  resourceNames:
  - {{ include "fe-docs.name" . }}
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "fe-docs.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    app: {{ include "fe-docs.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "fe-docs.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "fe-docs.name" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
