apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: happa-pull-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: happa
data:
  .dockerconfigjson: {{ .Values.Installation.V1.Secret.Registry.PullSecret.DockerConfigJSON | b64enc | quote }}
